---
app:
  base: #The Base Information of this MS
    name: eloanMS
    version: v01
    applicationId: eloan
    secret: secret
  env:
    KEY_1: VALUE_1
    KEY_2: VALUE_2	
  webMessageFilter:
    - id: filter1
      implementClass: com.cs.baseapp.api.filter.DefaultMsgProcWebFilter #com.cs.baseapp.api.filter.BaseMessageFilter
      desc: eloan filter 1
      urlPattern: /*
      parameters:
        KEY_1: value1
        KEY_2: value2
  messageBroker:
    sender:
    - id: rest-sender
      desc: rest sender
      implementClass: com.cs.baseapp.api.messagebroker.entity.DefaultRestSender #com.cs.baseapp.api.messagebroker.MessageSender
      poolSize: -1
      parameters:
        restType: formData
        KEY_2: value2
    - id: jms-sender
      desc: eloan jms sender
      implementClass: com.cs.baseapp.api.messagebroker.entity.DefaultJMSSender #com.cs.baseapp.api.messagebroker.MessageSender
      poolSize: 20
      parameters:
        KEY_1: value1
        KEY_2: value2
    receiver:
    - id: jms-receiver
      desc: eloan limit jms receiver
      implementClass: com.cs.baseapp.api.messagebroker.entity.DefaultJMSReceiver #com.cs.baseapp.api.messagebroker.MessageReceiver
      poolSize: 10
      parameters:
        timeout: 100
        KEY_2: value
    listener:
    - id: eloan-jms-lintenr
      desc: eloan jms listener
      implementClass: com.cs.baseapp.api.messagebroker.entity.DefaultJMSListener #com.cs.baseapp.api.messagebroker.MessageListener
      messageFilter: com.cs.baseapp.api.filter.DefaultListenerFilter #com.cs.baseapp.api.filter.BaseMessageFilter
      tranformClass: com.cs.baseapp.api.messagebroker.entity.DefaultTranslationMessage #com.cs.baseapp.api.messagebroker.TranslationMessage
      maxProcessThreads: 20
      parameters:
        queueName: EE_CE_Queue
        KEY_2: value
    services:
      local:
      - id: eloan-accrue
        implementClass: com.cs.demo.Accrue #com.cs.baseapp.api.messagebroker.BusinessService
        parameters:
          KEY_1: value1
          KEY_2: value2
      - id: eloan-posting
        implementClass: com.cs.demo.Accrue #com.cs.baseapp.api.messagebroker.BusinessService
        parameters:
          KEY_1: value1
          KEY_2: value2
      remote:
      - id: std-exchangeRate
        tranformClass: com.cs.baseapp.api.messagebroker.entity.DefaultTranslationMessage #com.cs.baseapp.api.messagebroker.TranslationMessage
        senderId: rest-sender
        receiverId: 
        parameters:
          KEY_1: value1
          KEY_2: value2
      - id: tp-service
        tranformClass: com.cs.baseapp.api.messagebroker.entity.DefaultTranslationMessage #com.cs.baseapp.api.messagebroker.TranslationMessage
        senderId: jms-sender
        receiverId: jms-receiver
        parameters:
          KEY_1: value1
          KEY_2: value2